# Generated by Django 4.2.29 on 2026-03-08 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_civil', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=100)),
                ('naturalidade_municipio', models.CharField(max_length=100)),
                ('naturalidade_uf', models.CharField(max_length=2)),
                ('rg', models.CharField(max_length=30)),
                ('rg_orgao_emissor', models.CharField(max_length=20)),
                ('rg_uf', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('data_ingresso', models.DateField()),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('data_defesa', models.DateField()),
                ('data_conclusao', models.DateField()),
                ('carga_horaria_total', models.IntegerField()),
                ('coorientador_nome', models.CharField(blank=True, max_length=200)),
                ('resumo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Rascunho', 'Rascunho'), ('Aguardando Coordenador', 'Aguardando Coordenador'), ('Aguardando PROPG', 'Aguardando PROPG'), ('Aprovado PROPG', 'Aprovado PROPG'), ('XML Gerado', 'XML Gerado'), ('Assinado (Simulado)', 'Assinado (Simulado)'), ('Registrado', 'Registrado'), ('Emitido', 'Emitido')], default='Rascunho', max_length=50)),
                ('numero_diploma', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('numero_livro', models.CharField(blank=True, max_length=10)),
                ('numero_folha', models.CharField(blank=True, max_length=10)),
                ('numero_registro', models.CharField(blank=True, max_length=20)),
                ('url_diploma', models.CharField(blank=True, max_length=255)),
                ('codigo_validacao', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('xml_gerado', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('defesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.defesa')),
            ],
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('lattes', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=20)),
                ('nivel', models.CharField(choices=[('MESTRADO_ACADEMICO', 'Mestrado Acadêmico'), ('MESTRADO_PROFISSIONAL', 'Mestrado Profissional'), ('DOUTORADO', 'Doutorado')], max_length=30)),
                ('codigo_sucupira', models.CharField(max_length=20)),
                ('area_capes', models.CharField(max_length=100)),
                ('modalidade', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('EAD', 'EaD'), ('HIBRIDO', 'Híbrido')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=50)),
                ('nome_assinante', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=45)),
                ('observacao', models.TextField(blank=True)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.diploma')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orientador'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.programa'),
        ),
    ]
